# Generated by Django 3.2 on 2021-04-24 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
