# Generated by Django 3.2 on 2021-04-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210425_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
